---
title: "Analysys_Behavior"
author: "山本寛樹"
date: "2015年12月14日"
output:
  pdf_document:
    latex_engine: xelatex
  html_document: default
monofont: Meiryo
mainfont: Meiryo
---
```{r, message=FALSE}
library(readr)
library(plyr)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(pipeR)
```

```{r}
# BehaviorDataの取得・各BehaviorDataのcsvの統合
files <- list.files(getwd(), recursive=T, pattern="TB_")
files[str_detect(files, pattern = "CSV/")] %>>%
  ldply(read_csv) -> df_behav

# observation.csvの処理
df_obs <- read_csv("C:/Users/yamamoto/Desktop/Observation.csv")
df_obs$Obs <- as.Date(df_obs$Obs)
df_obs %>>%
  select(NameID, Obs, ObsID, AgeinDays, Months, Days) -> df_obs

# DataFrameの統合
left_join(df_behav, df_obs, by = "ObsID") %>>%
  rename(Observe = Obs) -> df
```

```{r}
# 月齢を前半と後半に分ける
df %>>%
  mutate(AgeinMonths = ifelse(Days <= 14, Months, Months + 0.5)) -> df

# 例外処理
df$AgeinMonths[str_detect(df$ObsID, pattern = "KINOTU151104")] <- 13
```

# 要約統計量を算出
```{r}
df %>>%
  group_by(NameID, AgeinMonths) %>>%
  summarise(ObsID = first(ObsID),
            Observe = first(Observe),
            ObsTime = n(),
            Presence = ObsTime - sum(abscence),
            Move = (sum(crawl) + sum(cruise) + sum(walk)) / Presence * 100,
            Crawl = sum(crawl) / Presence * 100,
            Cruise = sum(cruise) / Presence * 100,
            Walk = sum(walk) / Presence * 100,
            Crawl_Move3 = sum(crawl) / (sum(crawl) + sum(cruise) + sum(walk)) * 100,
            Cruise_Move3 = sum(cruise) / (sum(crawl) + sum(cruise) + sum(walk)) * 100,
            Walk_Move3 = sum(walk) / (sum(crawl) + sum(cruise) + sum(walk)) * 100,
            Crawl_Move2 = sum(crawl) / (sum(crawl) + sum(walk)) * 100,
            Walk_Move2 = sum(walk) / (sum(crawl) + sum(walk)) * 100,
            pointing = sum(point_I),
            pointing_M = sum(point_M)
            ) -> data
```

## 運動時間割合の推移
```{r, fig.height=8, fig.width=9, echo=FALSE}
data %>>%
  ggplot(aes(x = AgeinMonths, y = Move, fill = NameID)) +
  geom_bar(stat = "identity") +
  ylim(0, 100) +
  facet_grid(NameID ~ .) +
  labs(title = "Developmental Change of Moving Time Proportion",
       y = "Proportion of time (%)") +
  scale_x_continuous(breaks = seq(min(data$AgeinMonths), max(data$AgeinMonths), by=0.5))
```

\newpage

## 観察時間(母親の視界内に乳児がいた時間)中の運動時間割合
```{r, echo=FALSE}
# グラフパラメーター
PT = 2
ATT = 1.75
ATX = 1.5
LTT = 2
LTX = 1.75
FTX = 1.75
```


```{r, fig.height=9, fig.width=11, echo=FALSE}
data %>>%
  gather(key = MovingStyle, value = Proportion, Crawl, Cruise, Walk) %>>%
  ggplot(aes(x = MovingStyle, y = Proportion, fill = MovingStyle)) +
  geom_bar(stat = "identity") +
  facet_grid(NameID ~ AgeinMonths) +
  labs(title = "Moving Time / Time in mother's view",
       y = "Proportion of time (%)",
       fill = "Moving\nStyle") +
  theme(axis.text = element_text(face = "bold")) +
  theme(plot.title = element_text(size = rel(PT), lineheight = 0.5, face = "bold"),
        axis.title = element_text(size = rel(ATT), face = "bold"),
        axis.text = element_text(size = rel(ATX), colour = "grey25")
        ) +
  theme(legend.title = element_text(size = rel(LTT), face = "bold"),
        legend.text = element_text(size = rel(LTX), face = "bold")
        ) +
  theme(strip.text = element_text(size = rel(FTX), face = "bold")) +
  theme(axis.text.x = element_blank())
```

\newpage

## 運動時間中の各移動方法の割合(Crawl, Cruise, Walk)
```{r, fig.height=8, fig.width=9, echo=FALSE}
data %>>%
  gather(key = MovingStyle, value = Proportion, Crawl_Move3, Cruise_Move3, Walk_Move3) %>>%
  ggplot(aes(x = AgeinMonths, y = Proportion, fill = MovingStyle)) +
  geom_bar(stat = "identity") +
  facet_grid(NameID ~.) +
  scale_fill_discrete(labels = c("Crawl", "Cruise", "Walk")) +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(title = "Proportion of each Moving Style / Moving Time",
       y = "Proportion (%)") +
  scale_x_continuous(breaks = seq(min(data$AgeinMonths), max(data$AgeinMonths), by=0.5))
```

\newpage

## 運動時間中の各移動方法の割合(Crawl, Walk)
```{r, fig.height=8, fig.width=9, echo=FALSE}
data %>>%
  gather(key = MovingStyle, value = Proportion, Crawl_Move2, Walk_Move2) %>>%
  ggplot(aes(x = AgeinMonths, y = Proportion, fill=MovingStyle)) +
  geom_bar(stat = "identity") +
  facet_grid(NameID ~.) +
  scale_fill_discrete(labels = c("Crawl", "Walk")) +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(title = "Proportion of each Moving Style / Moving Time",
       y = "Proportion (%)") +
  scale_x_continuous(breaks = seq(min(data$AgeinMonths), max(data$AgeinMonths), by=0.5))
```

\newpage

## とりあえず歩行児とハイハイ児に分けてみる
```{r, fig.height=8, fig.width=9, echo=FALSE}
data %>>%
  mutate(MovingStyle=ifelse(Crawl_Move2 >= 50, "Crawler", "Walker")) %>>%
  ggplot(aes(x = AgeinMonths, y = Move, fill = MovingStyle)) +
  geom_bar(stat = "identity") +
  ylim(0, 100) +
  facet_grid(NameID ~ .) +
  labs(title = "Developmental Change of Moving Time Proportion",
       y = "Proportion of time (%)") +
  scale_x_continuous(breaks = seq(min(data$AgeinMonths), max(data$AgeinMonths), by=0.5))
```

\newpage

## 同じ歩行割合でグラデーション
```{r, fig.height=8, fig.width=9, echo=FALSE}
data %>>%
  mutate(MovingStyle=ifelse(Crawl_Move2 >= 50, "Crawler", "Walker")) %>>%
  ggplot(aes(x = AgeinMonths, y = Move, fill = Walk_Move2)) +
  geom_bar(stat = "identity") +
  ylim(0, 100) +
  facet_grid(NameID ~ .) +
  labs(title = "Developmental Change of Moving Time Proportion",
       y = "Proportion of time (%)",
       fill = "Walk Prop") +
  scale_x_continuous(breaks = seq(min(data$AgeinMonths), max(data$AgeinMonths), by=0.5))
```

## CSV出力
```{r, eval=FALSE}
data %>>%
  write_csv("summarizeBehavior.csv")
```

