---
title: "Analysys_Distance"
author: "山本寛樹"
date: "2015年12月16日"
output:
  pdf_document:
    latex_engine: xelatex
  html_document: default
monofont: Meiryo
mainfont: Meiryo
---
```{r, message=FALSE}
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(readr)
library(stringr)
library(pipeR)
options(dplyr.print_max = 1e9, dplyr.width = Inf) # dplyrの表示オプション
```

```{r}
list.files(getwd(),pattern = 'Summary_', recursive=T, include.dirs=T)[1] %>>%
   read_csv() %>>%
   head()
```


```{r}
# summarizeBehavor.csv取得
read_csv("C:/Users/yamamoto/Documents/Fieldwork_data/BehaviorData/summarizeBehavior.csv") %>>%
  select(-AgeinMonths, -Observe) -> df_sum_behav


# 関数定義
modifyCSVFormat <- function(d_name){
  read_csv(d_name) %>>%
    mutate(Video = str_sub(d_name, start = -18, end = -5),
           ObsID = str_sub(d_name, start = -18, end = -7))
}

# サブディレクトリも含めて, 'Summary_'から始まるcsvファイルをすべて取得・縦方向に結合
list.files(getwd(),pattern = 'Summary_', recursive=T, include.dirs=T) %>>%
  ldply(modifyCSVFormat) %>>%
  left_join(df_sum_behav, by = c("NameID", "ObsID")) -> df
```

```{r}
# 月齢を前半と後半に分ける
df %>>%
  mutate(AgeinMonths = ifelse(Days <= 14, Months, Months + 0.5)) -> df

# 例外処理
df$AgeinMonths[str_detect(df$ObsID, pattern = "KINOTU151104")] <- 13
```

```{r}
# 各列の欠損値の有無を確認
df %>>%
  select(NameID, AgeinMonths, Distance, Duration, starts_with("Crawl"), starts_with("Cruise"), starts_with("Walk")) %>>%
  summarise_each(funs(anyNA))
```

\newpage

```{r}
df %>>%
  select(NameID, AgeinMonths, Distance, Duration, starts_with("Crawl"), starts_with("Cruise"), starts_with("Walk")) %>>%
  na.omit() %>>%
  filter(Duration > 0 & Duration  <= 10000 & Distance <= 4) %>>%
  mutate(MovingStyle = ifelse(Crawl_Move2 >= 50, "Crawler", "Walker")) %>>%
  group_by(NameID, AgeinMonths) %>>%
  summarise(N = n(),
            Mean = mean(Distance),
            SD = sd(Distance),
            SE = SD / sqrt(N),
            MovingStyle = first(MovingStyle)
            ) -> df_dist
```

\newpage

## アイコンタクトの生起距離の発達変化(line)
```{r}
# グラフパラメーター
PT = 2
ATT = 1.75
ATX = 1.5
LTT = 2
LTX = 1.75
FTX = 1.8
```


```{r, fig.height=8, fig.width=7, fig.align='center', echo=FALSE}
df_dist %>>%
  ggplot(aes(x = AgeinMonths, y = Mean)) +
  geom_line(aes(colour = NameID), lwd = 1.2, lty = 2) +
  geom_errorbar(aes(max = Mean + SE, min = Mean - SE, colour = NameID), width = 0.2, lwd = 1.2, lty = 1) +
  geom_point(aes(fill = MovingStyle), shape = 21, size = 5) +
  facet_grid(NameID~.) +
  labs(y = "Distance (m)",
       title = "Developmental Change of Eye Contact Distance",
       fill = "Moving\nStyle") +
  scale_x_continuous(breaks = seq(min(df$AgeinMonths), max(df$AgeinMonths), by=0.5)) +
  scale_fill_manual(values = c("white", "grey50")) +
  theme(plot.title = element_text(size = rel(PT), lineheight = 0.5, face = "bold"),
        axis.title = element_text(size = rel(ATT), face = "bold"),
        axis.text = element_text(size = rel(ATX), face = "bold", colour = "grey25"),
        axis.text.x = element_text(size = rel(1.2))
        ) +
  theme(legend.title = element_text(size = rel(LTT), face = "bold"),
        legend.text = element_text(size = rel(LTX), face = "bold")
        ) +
  theme(strip.text.y = element_text(size = rel(FTX), face = "bold"))
```

\newpage

## アイコンタクトの生起距離の発達変化(violin plot)

```{r, fig.height=8, fig.width=7, fig.align='center', echo=FALSE}
df %>>%
  filter(Duration > 0 & Duration <= 10000 & Distance <= 4) %>>%
  select(NameID, AgeinMonths, Distance, Duration, starts_with("Crawl"), starts_with("Cruise"), starts_with("Walk")) %>>%
  na.omit() %>>%
  mutate(MovingStyle = ifelse(Crawl_Move2 >= 50, "Crawler", "Walker")) %>>%
  ggplot(aes(x = as.character(AgeinMonths), y = Distance, colour = NameID)) +
  geom_violin(aes(fill = MovingStyle), lwd = 1) +
  stat_summary(fun.y = median, geom = "point", shape = 19, size = 3) +
  facet_grid(NameID~.) +
  labs(x = "Months",
       y = "Distance (m)",
       title = "Developmental Change of Eye Contact Distance (Horizontal)") +
  scale_fill_manual(values = c("white", "grey50")) 
```

\newpage

## アイコンタクトの生起距離の発達変化(histogram)

```{r, fig.height=8, fig.width=9, echo=FALSE}
df %>>%
  filter(Duration > 0 & Duration <= 10000 & Distance <= 4) %>>%
  select(NameID, AgeinMonths, Distance, Duration, starts_with("Crawl"), starts_with("Cruise"), starts_with("Walk")) %>>%
  na.omit() %>>%
  mutate(MovingStyle=ifelse(Crawl_Move2 >= 50, "Crawler", "Walker")) %>>%
  ggplot(aes(x = Distance, colour = NameID, fill = MovingStyle)) +
  geom_histogram(binwidth = 0.25) +
  facet_grid(AgeinMonths ~ NameID) +
  labs(title = "Developmental Change of Eye Contact Distance (Horizontal)") +
  scale_fill_manual(values = c("white", "grey50")) +
  scale_x_continuous(breaks = seq(0, 5, by=1), limits=c(0, 5))
```

\newpage

## アイコンタクトの生起距離の発達変化(denisty plot)

```{r, fig.height=8, fig.width=9, echo=FALSE}
df %>>%
  filter(Duration > 0 & Duration <= 10000 & Distance <= 4) %>>%
  select(NameID, AgeinMonths, Distance, Duration, starts_with("Crawl"), starts_with("Cruise"), starts_with("Walk")) %>>%
  na.omit() %>>%
  mutate(MovingStyle = ifelse(Crawl_Move2 >= 50, "Crawler", "Walker")) %>>%
  ggplot(aes(x = Distance, colour = NameID, fill = MovingStyle)) +
  geom_density(lwd = 1) +
  facet_grid(AgeinMonths ~ NameID) +
  labs(title = "Developmental Change of Eye Contact Duration") +
  scale_fill_manual(values = c("white", "grey50")) +
  scale_x_continuous(breaks = seq(0, 5, by=1), limits=c(0, 5)) 
```

\newpage

## 距離と時間長の相関
```{r, fig.height=8, fig.width=9, echo=FALSE}
df %>>%
  filter(Duration > 0 & Duration <= 10000 & Distance <= 4) %>>%
  select(NameID, AgeinMonths, Distance, Duration, starts_with("Crawl"), starts_with("Cruise"), starts_with("Walk")) %>>%
  na.omit() %>>%
  mutate(MovingStyle=ifelse(Crawl_Move2 >= 50, "Crawler", "Walker")) %>>%
  ggplot(aes(x = Distance, y = Duration, colour = NameID)) +
  geom_point(aes(shape = MovingStyle), size = 2, stroke = 1) +
  facet_grid(AgeinMonths ~ NameID, scales = "free_x") +
  labs(title = "Relation of Eye Contact Distance & Eye Contact Duration") +
  scale_x_continuous(breaks = seq(0, 5, by=1), limits=c(0, 5)) +
  scale_shape_manual(values=c(21, 22)) +
  stat_smooth(method = "glm", method.args = list(family = "Gamma"(link = "log")), se = FALSE, lwd = 1.2)
```


