---
title: "preprocess2"
author: "Hiroki YAMAMOTO"
date: "2015.06.26"
output: html_document
---
```{r}
library(plyr)
library(dplyr)
library(stringr)
library(pipeR)
options(dplyr.print_max = 1e9) # dplyrの表示オプション
```

```{r}
# unpreprocDataを取得
file_nameUP <-list.files(getwd(), pattern='unprocData_')

if(length(file_nameUP) != 0)
  {
  dataUP <- read.csv(file_nameUP)
}

dataUP$SessionID <- as.factor(dataUP$SessionID)
dataUP$EventID <- as.factor(dataUP$EventID)
dataUP$FrameID <- as.factor(dataUP$FrameID)
dataUP$RotateID <- as.factor(dataUP$RotateID)
```

###データの取得

```{r}
# AnnotationDataを取得
HD <- getwd()
setwd("AnnotationAssistant/DBOutput")

file_nameAN <-list.files(getwd(), pattern='Annotation')

if(length(file_nameAN) != 0)
  {
  dataAN <- read.csv(file_nameAN)
  }

setwd(HD)
```

###データの置換
```{r}
# imgpathからEventID, FrameID, RotateIDを取得 
dataAN$imgpath <- as.character(dataAN$imgpath)

dataAN %>>%
  mutate(EventID = character(nrow(dataAN)),
         FrameID = character(nrow(dataAN)),
         RotateID = character(nrow(dataAN))
         ) -> dataAN

for(i in 1:nrow(dataAN))
  {
  IDs <- str_split(dataAN$imgpath[i], pattern = 'Event')[[1]][2]
  eID <- str_split(IDs, pattern = fixed('.'))[[1]][1]
  fID <- str_split(IDs, pattern = fixed('.'))[[1]][2]
  rID <- str_split(IDs, pattern = fixed('.'))[[1]][3]
  
  dataAN$EventID[i] <- eID
  dataAN$FrameID[i] <- as.character(ifelse(str_detect(fID, pattern = 'm'),
                                           as.numeric(str_split(fID, pattern = 'm')[[1]][1]) * (-1),
                                           fID)
                                    )
  dataAN$RotateID[i] <- as.character(ifelse(str_detect(rID, pattern = 'm'), 
                                            as.numeric(str_split(rID, pattern = 'm')[[1]][1]) * (-1),
                                            rID)
                                     )
}

#dataAN$EventID <- as.factor(dataAN$EventID)
#dataAN$FrameID <- as.factor(dataAN$FrameID)
#dataAN$RotateID <- as.factor(dataAN$RotateID)
```

```{r}
# rowdataの置換
for(i in 1:nrow(dataAN))
  {
  eID <- dataAN$EventID[i]
  fID <- dataAN$FrameID[i]
  rID <- dataAN$RotateID[i]
  
  dataUP$FaceID[dataUP$EventID == eID & dataUP$FrameID == fID & dataUP$RotateID == rID] <- 1
  dataUP$pos_x[dataUP$EventID == eID & dataUP$FrameID == fID & dataUP$RotateID == rID] <- dataAN$x[i]
  dataUP$pos_y[dataUP$EventID == eID & dataUP$FrameID == fID & dataUP$RotateID == rID] <- dataAN$y[i]
  dataUP$Width[dataUP$EventID == eID & dataUP$FrameID == fID & dataUP$RotateID == rID] <- dataAN$width[i]
  dataUP$Height_rmv[dataUP$EventID == eID & dataUP$FrameID == fID & dataUP$RotateID == rID] <- dataAN$height[i]
  }
```

###データフレームの編集

```{r}
video_name <-list.files(getwd(), pattern='.mp4')
file_id <- str_split(video_name, pattern='.mp4')[[1]][1]
file_id <- str_split(file_id, pattern='TB_')[[1]][2]

# infantIDを取得
name_id <- str_sub(file_id, start=1, end=6)

# 調査日を取得
year <- str_c("20", str_sub(file_id, start=7, end=8))
month <- str_sub(file_id, start=9, end=10)
day <- str_sub(file_id, start=11, end=12)
strdate <- str_c(year, month, day, sep="-")
obs <- as.POSIXct(strdate)

# 日齢・月齢計算
birthday <- read.csv("C:/Users/yamamoto/Desktop/infants.csv")
birth <- as.POSIXct(birthday$Birth[birthday$NameID == name_id])
AiD <- length(seq(as.Date(birth), as.Date(obs), "day")) - 1 # AgeinDays
AiM <- length(seq(as.Date(birth), as.Date(obs), "month")) - 1 # AgeinMonth


dataUP %>>%
  group_by(SessionID) %>>%
  summarise(Eve_lev = length(levels(droplevels(EventID))),
            Fra_lev = length(levels(FrameID)), # SessionあたりのFrameIDの数
            Rot_lev = length(levels(RotateID)), # SessiontあたりのRotateIDの数
            pic_num = Eve_lev * Fra_lev * Rot_lev, # SessionあたりのFace Detectionを実施した画像数
            ano_num = n(), # Sessionあたりのannotationの数
            Miss = sum(is.na(FaceID)), # Eventあたりの, 顔を検出できなかった画像の数
            Removed = sum(FaceID == 0, na.rm=TRUE), # 無効化されたannotationの数
            Detect = ano_num - Miss - Removed, # Eventあたりの, (FAも含まれるかもしれないが)顔を検出できた画像の数
            allMiss = ifelse(Miss + Removed == ano_num, 1, 0), # ひとつも顔が検出されないEventであるかどうか
            multiFace = ifelse(max(FaceID, na.rm=TRUE) >= 2, 1, 0), # Event内の画像に, 複数の顔が検出されることがあるかどうか
            Mean = mean(Height, na.rm=TRUE),
            Mean_rmv = mean(Height_rmv, na.rm=TRUE),
            SD = sd(Height, na.rm=TRUE),
            SD_rmv = sd(Height_rmv, na.rm=TRUE),
            Duration = max(GazeTimeStamp, na.rm=TRUE) - min(GazeTimeStamp, na.rm=TRUE)
            ) %>>%
  mutate(Name = factor(name_id),
               Observe = obs,
               AgeinDays = AiD,
               AgeinMonth = AiM,
               Video = factor(file_id)
               ) -> df_Session
df_Session <- df_Session[c(17:21, 1:16)] 
complete <- 1

```

###データフレームの保存 

```{r}
if(complete != 0)
  {
  file_nameD <- paste("processedData_", file_id, ".csv", sep="")
  file_nameS <- paste("Session_", file_id, ".csv", sep="")

  # 前処理後(Sessionの付与・外れ値の除去・複数検出されたAnnotationの無効化)の"Face_ (file_id) .csv" のデータを保存
  write.csv(dataUP, file_nameD, quote = FALSE, row.names = FALSE)

  # 前処理後のデータをSessionごとに要約した結果をcsvで保存 
  write.csv(df_Session, file_nameS, quote = FALSE, row.names = FALSE)
  }
```
