---
title: "preprocess2"
author: "Hiroki YAMAMOTO"
date: "2015.06.26"
output: html_document
---
```{r}
library(plyr)
library(dplyr)
library(stringr)
library(readr)
library(pipeR)
options(dplyr.print_max = 1e9, dplyr.width = Inf) # dplyrの表示オプション
```

```{r}
# 乳児のNameIDを取得
list.files(getwd(), pattern='.mp4')[1] %>>%
  str_sub(start = 4, end = 9) -> name_id

# 乳児の顔サイズを取得
read_csv("C:/Users/yamamoto/Desktop/infantsFace.csv") %>>%
  filter(NameID == name_id) %>>%
  (FaceSize) -> face_size 


# 水平状態でのglassの角度 (degree)
deg_default <- 3.739802
# deg_default <- 0 # 補正なし

# カメラ・パラメーター
df_par <- read_csv("C:/Users/yamamoto/Desktop/CameraParameter.csv")
beta <- df_par$Mean[df_par$Parameter == 'beta']
pw <- df_par$Mean[df_par$Parameter == 'pw']
```

###FaceDataの取得

```{r}
# Face_csvを取得
file_nameUP <-list.files(getwd(), pattern='Face_')

if(length(file_nameUP) != 0){
  df_face <- read_csv(file_nameUP)
}

df_face$pos_x <- as.numeric(df_face$pos_x)
df_face$pos_y <- as.numeric(df_face$pos_y)
df_face$Width <- as.numeric(df_face$Width)
df_face$Height <- as.numeric(df_face$Height)

df_face$EventID <- as.factor(df_face$EventID)
df_face$RotateID <- as.factor(df_face$RotateID)
```

###AnnotationDataの取得

```{r}
HD <- getwd()
# AnnotationDataを取得
setwd("AnnotationAssistant/DBOutput")

file_nameAN <-list.files(getwd(), pattern='Annotation')

if(length(file_nameAN) != 0){
  dataAN <- read_csv(file_nameAN)
}

setwd(HD)
```

### 画像パスからEventID, RotateIDを読み取り, AnnotationDataに追加
```{r}
# imgpathからEventID, FrameID, RotateIDを取得 
# dataAN$imgpath <- as.character(dataAN$imgpath)

dataAN %>>%
  mutate(EventID = character(nrow(dataAN)),
         RotateID = character(nrow(dataAN))
         ) -> dataAN

for(i in 1:nrow(dataAN))
  {
  IDs <- str_split(dataAN$imgpath[i], pattern = '_')[[1]][4]
  eID <- str_split(IDs, pattern = fixed('.'))[[1]][2]
  rID <- str_split(IDs, pattern = fixed('.'))[[1]][3]
  
  dataAN$EventID[i] <- eID
  dataAN$RotateID[i] <- as.character(ifelse(str_detect(rID, pattern = 'm'), 
                                            as.numeric(str_split(rID, pattern = 'm')[[1]][1]) * (-1),
                                            rID)
                                     )
}

#dataAN$EventID <- as.factor(dataAN$EventID)
#dataAN$RotateID <- as.factor(dataAN$RotateID)
```

# AnnotationDataのEventID, RotateIDをもとにFaceDataの値を更新
```{r}
# rowdataの置換
for(i in 1:nrow(dataAN))
  {
  eID <- dataAN$EventID[i]
  rID <- dataAN$RotateID[i]
  
  df_face$pos_x[df_face$EventID == eID & df_face$RotateID == rID] <- dataAN$x[i]
  df_face$pos_y[df_face$EventID == eID & df_face$RotateID == rID] <- dataAN$y[i]
  df_face$Width[df_face$EventID == eID & df_face$RotateID == rID] <- dataAN$width[i]
  df_face$Height[df_face$EventID == eID & df_face$RotateID == rID] <- dataAN$height[i]
  }
```

###FaceDaraデータフレームの編集
```{r}
# videoIDを取得
list.files(getwd(), pattern='.mp4')[1] %>>%
  str_sub(start = 4, end=-5) -> video_id

# ObsIDを取得
list.files(getwd(), pattern='.mp4')[1] %>>%
  str_sub(start = 4, end=15) -> obs_id

# 調査日(Obs)を取得
str_sub(obs_id, start = 7) %>>%
  as.Date(format="%y%m%d") -> obs


# 日齢・月齢計算
read_csv("C:/Users/yamamoto/Desktop/Observation.csv") %>>%
  filter(ObsID == obs_id) -> df_obs


df_face %>>%
  group_by(EventID) %>>%
  summarise(Rot_lev = length(levels(RotateID)), # SessiontあたりのRotateIDの水準数
            Mean = mean(Height, na.rm=TRUE), # Sessionあたりのannotationサイズの平均
            SD = sd(Height, na.rm=TRUE), # Sessionあたりのannotationサイズの標準偏差
            Duration = mean(Duration, na.rm=TRUE), # Sessionの時間長
            Deg = mean(Degree, na.rm=TRUE),
            Distance = beta * face_size * Mean ^ pw * cos((Deg - deg_default) * pi / 180),
            EventTime = first(EventTime), # おそらくOK
            GazeTimeStamp = first(GazeTimeStamp)
            ) %>>%
  mutate(NameID = name_id,
         Observe = obs,
         ObsID = obs_id,
         AgeinDays = df_obs$AgeinDays,
         AgeinMonth = df_obs$Months,
         Days = df_obs$Days,
         Video = video_id
         ) -> df_summary
df_summary <- df_summary[c(10:12, 16, 13:15, 8:9, 1:7)] 
complete <- 1

```

###データフレームの保存 

```{r}
if(complete != 0)
  {
  file_nameF <- paste("Face_", video_id, ".csv", sep="")
  file_nameS <- paste("Summary_", video_id, ".csv", sep="")

  # 前処理後(Sessionの付与・外れ値の除去・複数検出されたAnnotationの無効化)の"Face_ (file_id) .csv" のデータを保存
  write_csv(df_face, file_nameF)

  # 前処理後のデータをSessionごとに要約した結果をcsvで保存 
  write_csv(df_summary, file_nameS)
  }
```
