---
title: "Analysys"
author: "Hiroki YAMAMOTO"
date: "2015年6月17日"
output: html_document
---
```{r, message=FALSE}
library(plyr)
library(dplyr)
library(ggplot2)
library(stringr)
library(pipeR)
options(dplyr.print_max = 1e9) # dplyrの表示オプション
```

###Sessionを定義するtime intervalの閾値を決める

```{r, fig.height=6, fig.width=6}
# データを取得
file_name <-list.files(getwd(), pattern='Event_')
data <- read.csv(file_name)

# EyeContact Event間の時間差を計算
int <- diff(data$Recording.timestamp)
length(int)

# time intervalのヒストグラム
fRate <- 50
b_wid <- 1000 / fRate

int %>>%
  as.data.frame() %>>%
  ggplot(aes(x = int)) +
  geom_histogram(binwidth = b_wid) +
  xlim(0, 4000) + 
  labs(title = "Time Interval between Eye Contact Events", x = "Time Interval (msec)") 

thr <- 1000
sum(int <= thr) / length(int) * 100
```

\   

###各Session・Eventについて, 要約統計量を算出

Face Annotationのデータを読み込む. 

```{r}
# Face Annotation のデータを取得
file_name <-list.files(getwd(), pattern='Face_')
data <- read.csv(file_name)

thr <- 1000

data$SessionID <- rep(1, length = nrow(data))
for(i in 1:(nrow(data) - 1))
  {
  if (data$GazeTimeStamp[i + 1] - data$GazeTimeStamp[i] <= thr)
    {
    data$SessionID[i + 1] <- data$SessionID[i]
    }
  else
    {
    data$SessionID[i + 1] <- data$SessionID[i] + 1
    }
  }

data <- data[c(1, 16, 2:15)]

data$SessionID <- as.factor(data$SessionID)
data$EventID <- as.factor(data$EventID)
data$FrameID <- as.factor(data$FrameID)
data$RotateID <- as.factor(data$RotateID)
# data$FaceID <- as.factor(data$FaceID)
```

SessionごとにDetect数, Miss数などを算出

```{r}
data %>>%
  group_by(SessionID) %>>%
  summarise(Eve_lev = length(levels(droplevels(EventID))), # SessionあたりのEventIDの水準の数
            Fra_lev = length(levels(FrameID)), # SessionあたりのFrameIDの水準の数
            Rot_lev = length(levels(RotateID)), # SessiontあたりのRotateIDの水準数
            pic_num = Eve_lev * Fra_lev * Rot_lev, # SessionあたりのFace Detectionを実施した画像数
            ano_num = n(), # Sessionあたりの, 検出されたannotationの数
            Miss = sum(is.na(FaceID)), # Sessionあたりの, 顔を検出できなかった画像の数
            Detect = pic_num - Miss, # Sessionあたりの, (FAも含まれるかもしれないが)顔を検出できた画像の数
            allMiss = ifelse(Miss == pic_num, 1, 0), # ひとつも顔が検出されないEventであるかどうか
            multiFace = ifelse(max(FaceID, na.rm=TRUE) >= 2, 1, 0), # Event内の画像に, 複数の顔が検出されることがあるかどうか
            Mean = mean(Height, na.rm=TRUE),
            SD = sd(Height, na.rm=TRUE),
            Duration = max(GazeTimeStamp) - min(GazeTimeStamp)
            ) -> df_Session
#df_Session
```

EventごとにDetect数, Miss数などを算出

```{r}
data %>>%
  group_by(EventID, SessionID) %>>%
  summarise(Fra_lev = length(levels(FrameID)), # EventあたりのFrameIDの水準の数
            Rot_lev = length(levels(RotateID)), # EventあたりのRotateIDの水準の数
            pic_num = Fra_lev * Rot_lev, # EventあたりのFace Detectionを実施した画像数
            ano_num = n(), # Eventあたりの,検出されたannotationの数
            Miss = sum(is.na(FaceID)), # Eventあたりの, 顔を検出できなかった画像の数
            Detect = pic_num - Miss, # Eventあたりの, (FAも含まれるかもしれないが)顔を検出できた画像の数
            allMiss = ifelse(Miss == pic_num, 1, 0), # ひとつも顔が検出されないEventであるかどうか
            multiFace = ifelse(max(FaceID, na.rm=TRUE) >= 2, 1, 0) # Event内の画像に, 複数の顔が検出されることがあるかどうか
            ) -> df_Event
#df_Event
```

###顔検出器の性能を評価する
```{r}
# Event数
nrow(df_Event)

# Detect率
sum(df_Event$Detect >= 1) / nrow(df_Event) * 100

# Miss率
sum(df_Event$allMiss == 1) / nrow(df_Event) * 100
```

###外れ値の除去

```{r}
data$Height_rmv <- data$Height
remove_id <- numeric()
prop_SD <- 2

for (i in 1:nrow(data))
  {
  session <- data[i, "SessionID"]
  df_Session %>>%
  filter(SessionID == session) %>>%
  select(Mean, SD) -> sss
  
  if (is.nan(sss$Mean) == F && is.nan(sss$SD) == F && is.na(data$Height[i]) == F)
    {
    if (data$Height[i] > sss$Mean + prop_SD * sss$SD || data$Height[i] < sss$Mean - prop_SD * sss$SD)
      {
      data$FaceID[i] <- 0
      data$Height_rmv[i] <- NA
      data$GazeTimeStamp[i] <- NA
      remove_id <- c(remove_id, i)
      }
    }
  }

data <- data[c(1:15, 17, 16)]
length(remove_id) # 外れ値として除去されたannotation dataの数
```

###再びSessionごとの要約統計量を算出

```{r}
data %>>%
  group_by(SessionID) %>>%
  summarise(Eve_lev = length(levels(droplevels(EventID))), # SessionあたりのEventIDの水準の数
            Fra_lev = length(levels(FrameID)), # SessionあたりのFrameIDの水準の数
            Rot_lev = length(levels(RotateID)), # SessionあたりのRotateIDの水準の数
            pic_num = Eve_lev * Fra_lev * Rot_lev, # SessionあたりのFace Detectionを実施した画像数
            ano_num = n(), # Sessionあたりのannotationの数
            Miss = sum(is.na(FaceID)), # Eventあたりの, 顔を検出できなかった画像の数
            Removed = sum(FaceID == 0, na.rm=TRUE), # 前処理で除去したannotationの数
            Detect = pic_num - Miss - Removed, # Eventあたりの, (FAも含まれるかもしれないが)顔を検出できた画像の数
            allMiss = ifelse(Miss + Removed == pic_num, 1, 0), # ひとつも顔が検出されないEventであるかどうか
            multiFace = ifelse(max(FaceID, na.rm=TRUE) >= 2, 1, 0), # Event内の画像に, 複数の顔が検出されることがあるかどうか
            Mean = mean(Height, na.rm=TRUE),
            Mean_rmv = mean(Height_rmv, na.rm=TRUE),
            SD = sd(Height, na.rm=TRUE),
            SD_rmv = sd(Height_rmv, na.rm=TRUE),
            Duration = max(GazeTimeStamp, na.rm=TRUE) - min(GazeTimeStamp, na.rm=TRUE)
            ) -> df_Session
#df_Session
```

###同一画像に複数のannotationがある画像について, annotationをすべて無効にする.

```{r}
data %>>%
  group_by(EventID, FrameID, RotateID, SessionID) %>>%
  summarise(rows = n(), # Sessionあたりの, 検出されたannotationの数
            FaceNum = max(FaceID, na.rm=TRUE),
            multiFace = ifelse(max(FaceID, na.rm=TRUE) >= 2, 1, 0) # Event内の画像に, 複数の顔が検出されることがあるかどうか
            ) %>>%
  filter(multiFace == 1) -> multiFace


if(nrow(multiFace) > 0)
  {
  for(i in 1:nrow(multiFace))
    {
     eID <- multiFace$EventID[i]
     fID <- multiFace$FrameID[i]
     rID <- multiFace$RotateID[i]
     
     data$FaceID[data$EventID == eID & data$FrameID == fID & data$RotateID == rID] <- 0
     data$Height_rmv[data$EventID == eID & data$FrameID == fID & data$RotateID == rID] <- NA
     data$GazeTimeStamp[data$EventID == eID & data$FrameID == fID & data$RotateID == rID] <- NA
    }
}

# 無効化された画像
nrow(multiFace)
```


###再度Sessionごとの要約統計量を算出

```{r}
data %>>%
  group_by(SessionID) %>>%
  summarise(Eve_lev = length(levels(droplevels(EventID))),
            Fra_lev = length(levels(FrameID)), # SessionあたりのFrameIDの数
            Rot_lev = length(levels(RotateID)), # SessiontあたりのRotateIDの数
            pic_num = Eve_lev * Fra_lev * Rot_lev, # SessionあたりのFace Detectionを実施した画像数
            ano_num = n(), # Sessionあたりのannotationの数
            Miss = sum(is.na(FaceID)), # Eventあたりの, 顔を検出できなかった画像の数
            Removed = sum(FaceID == 0, na.rm=TRUE), # 無効化されたannotationの数
            Detect = ano_num - Miss - Removed, # Eventあたりの, (FAも含まれるかもしれないが)顔を検出できた画像の数
            allMiss = ifelse(Miss + Removed == ano_num, 1, 0), # ひとつも顔が検出されないEventであるかどうか
            multiFace = ifelse(max(FaceID, na.rm=TRUE) >= 2, 1, 0), # Event内の画像に, 複数の顔が検出されることがあるかどうか
            Mean = mean(Height, na.rm=TRUE),
            Mean_rmv = mean(Height_rmv, na.rm=TRUE),
            SD = sd(Height, na.rm=TRUE),
            SD_rmv = sd(Height_rmv, na.rm=TRUE),
            Duration = max(GazeTimeStamp, na.rm=TRUE) - min(GazeTimeStamp, na.rm=TRUE)
            ) -> df_Session
df_Session
```


###検出画像が一切ないセッションの画像を選択

```{r}
video_name <-list.files(getwd(), pattern='.mp4')
file_id <- str_split(video_name, pattern='.mp4')[[1]][1]
file_id <- str_split(file_id, pattern='TB_')[[1]][2]

# infantIDを取得
name_id <- str_sub(file_id, start=1, end=6)

# 調査日を取得
year <- str_c("20", str_sub(file_id, start=7, end=8))
month <- str_sub(file_id, start=9, end=10)
day <- str_sub(file_id, start=11, end=12)
strdate <- str_c(year, month, day, sep="-")
obs <- as.POSIXct(strdate)

# 日齢・月齢計算
birthday <- read.csv("C:/Users/yamamoto/Desktop/infants.csv")
birth <- as.POSIXct(birthday$Birth[birthday$NameID == name_id])
AiD <- length(seq(as.Date(birth), as.Date(obs), "day")) - 1 # AgeinDays
AiM <- length(seq(as.Date(birth), as.Date(obs), "month")) - 1 # AgeinMonth


df_Session %>>%
  filter(allMiss == 1) %>>%
  select(SessionID) -> allMiss

if (nrow(allMiss) != 0)
  {
  data %>>%
    group_by(EventID, FrameID, RotateID, SessionID, Picture) %>>%
    summarise(N = n()) %>>%
    filter(SessionID %in% allMiss$SessionID) %>>%
    select(EventID, FrameID, RotateID, SessionID, Picture) %>>%
    mutate(Name = factor(name_id),
           Observe = obs,
           AgeinDays = AiD,
           AgeinMonth = AiM,
           Video = factor(file_id)
           ) -> Annot
  Annot <- Annot[c(6:10, 1:5)]  
  
  complete <- 0
  } else
    {
    df_Session %>>%
        mutate(Name = factor(name_id),
               Observe = obs,
               AgeinDays = AiD,
               AgeinMonth = AiM,
               Video = factor(file_id)
               ) -> df_Session
    df_Session <- df_Session[c(17:21, 1:16)] 
    print("すべてMissで構成されるSessionはない")
    
    complete <- 1
    }
```

###データフレームの保存


```{r}
if(complete != 0)
  {
  file_nameD <- paste("processedData_", file_id, ".csv", sep="")
  file_nameS <- paste("Session_", file_id, ".csv", sep="")
  
  # 前処理後(Sessionの付与・外れ値の除去・複数検出されたAnnotationの無効化)の"Face_ (file_id) .csv" のデータを保存
  write.csv(data, file_nameD, quote = FALSE, row.names = FALSE)
  
  # 前処理後のデータをSessionごとに要約した結果をcsvで保存 
  write.csv(df_Session, file_nameS, quote = FALSE, row.names = FALSE)
  
  } else
    {
    file_nameUP <- paste("unprocData_", file_id, ".csv", sep="")
    file_nameAN <- paste("Annot_", file_id, ".csv", sep="")  
    
    write.csv(data, file_nameUP, quote = FALSE, row.names = FALSE)
  
    # 前処理後のデータをSessionごとに要約した結果をcsvで保存 
    write.csv(Annot, file_nameAN, quote = FALSE, row.names = FALSE)
    }
```


