---
title: "Analysys"
author: "Hiroki YAMAMOTO"
date: "2015年6月17日"
output: html_document
---
```{r, message=FALSE}
library(plyr)
library(dplyr)
library(ggplot2)
library(stringr)
library(pipeR)
library(grid)
options(dplyr.print_max = 1e9) # dplyrの表示オプション

gg_color_hue <- function(n, l=65) {
  hues <- seq(15, 375, length=n+1)
  hcl(h=hues, l=l, c=100)[1:n]
}
```


###Sessionを定義するtime intervalの閾値を決める

```{r, fig.height=6, fig.width=6}
# データを取得
files <-list.files(getwd(), pattern='Event_')


df <- data.frame(file_name = character(0),
                 int = numeric(0)
                 )
for(i in 1:length(files))
{
  data <- read.csv(files[i])
  
  # infantIDを取得
  name_id <- str_sub(files[i], start=7, end=12)

  # 調査日を取得
  year <- str_c("20", str_sub(files[i], start=13, end=14))
  month <- str_sub(files[i], start=15, end=16)
  day <- str_sub(files[i], start=17, end=18)
  strdate <- str_c(year, month, day, sep="-")
  obs <- as.POSIXct(strdate)
  
  
  # EyeContact Event間の時間差を計算
  int <- diff(data$Recording.timestamp)
  df_int <- data.frame(name = name_id,
                       observ = obs,
                       file_name = files[i],
                       int = int)
  df <- rbind(df, df_int)
}


# time intervalのヒストグラム
fRate <- 50
b_wid <- 1000 / fRate

thr <- 1000

df %>>%
  group_by(name) %>>%
  summarise(Event_num = n() + 1,
            Percent = sum(int <= thr) / length(int) * 100
            )
```

```{r}
df %>>%
  ggplot(aes(x = int, fill = name)) +
  geom_histogram(binwidth = b_wid*2) +
  xlim(0, 5000) +
  facet_grid(name~.) +
  labs(title = "Time Interval between Eye Contact Events", x = "Time Interval (msec)")  +
  scale_fill_discrete(name="name",
                      breaks=c("INOKEI", "KOTAYU"),
                      labels=c("Walker\nINOKEI", "Crawler\nKOTAYU"))
```

```{r}
df %>>%
  ggplot(aes(x = int, fill = name)) +
  geom_histogram(binwidth = b_wid*2) +
  xlim(0, 5000) +
  coord_cartesian(ylim=c(0, 50)) +
  facet_grid(name~.) +
  labs(title = "Time Interval between Eye Contact Events", x = "Time Interval (msec)")  +
  scale_fill_discrete(name="name",
                      breaks=c("INOKEI", "KOTAYU"),
                      labels=c("Walker\nINOKEI", "Crawler\nKOTAYU"))
```



```{r}
gp1 <- df %>>%
  ggplot(aes(x = int, fill = name)) +
  geom_histogram(binwidth = b_wid*2) +
  xlim(0, 5000) +
  guides(fill=FALSE) +
  facet_grid(name~.) +
  labs(title = "Time Interval between Eye Contact Events", x = "Time Interval (msec)") 
print(gp1)

gp2 <- df %>>%
  ggplot(aes(x = int, fill = name)) +
  geom_histogram(binwidth = b_wid*2) +
  xlim(0, 5000) +
  coord_cartesian(ylim=c(0, 50)) +
  facet_grid(name~.) +
  labs(title = "Time Interval between Eye Contact Events", x = "Time Interval (msec)")  +
  scale_fill_discrete(name="name",
                      breaks=c("INOKEI", "KOTAYU"),
                      labels=c("Walker\nINOKEI", "Crawler\nKOTAYU"))
print(gp2)

grid.newpage()
pushViewport(viewport(layout=grid.layout(1, 2, width = c(0.4, 0.5)))) #画面を区切る（今回は2行2列の4分割）
print(gp1, vp=viewport(layout.pos.row=1, layout.pos.col=1)) 
print(gp2, vp=viewport(layout.pos.row=1, layout.pos.col=2)) 
```



```{r}
gp1 <- df %>>%
  ggplot(aes(x = int, fill = name)) +
  geom_histogram(binwidth = b_wid) +
  xlim(0, thr) + 
  facet_grid(name~.) +
  guides(fill=FALSE) +
  labs(title = "Time Interval between Eye Contact Events", x = "Time Interval (msec)")

gp2 <- df %>>%
  ggplot(aes(x = int, fill = name)) +
  geom_histogram(binwidth = b_wid*2) +
  xlim(thr, 7000) + 
  facet_grid(name~.) +
  labs(title = "Time Interval between Eye Contact Events", x = "Time Interval (msec)") +
  scale_fill_discrete(name="name",
                      breaks=c("INOKEI", "KOTAYU"),
                      labels=c("Walker\nINOKEI", "Crawler\nKOTAYU"))

grid.newpage()
pushViewport(viewport(layout=grid.layout(1, 2, width = c(0.4, 0.5)))) #画面を区切る（今回は2行2列の4分割）
print(gp1, vp=viewport(layout.pos.row=1, layout.pos.col=1)) 
print(gp2, vp=viewport(layout.pos.row=1, layout.pos.col=2)) 
```

